default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['PASSWORD'] %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: teachers_development

test:
  <<: *default
  database: teachers_test

production:
  <<: *default
  database: teachers_production
  username: root
  password: <%= ENV['PASSWORD'] %>
